### ISSUE TITLE
Keyboard shortcuts for Windows?

### ISSUE THREAD

**Issue by pixtur** [davidnussio/vscode-jq-playground#72]
I really love your extension. But for me the Ctrl+Enter hotkey doesn't work (it just inserts a new line). 
Is it supported under windows, too?

I'm using v4.1

Clicking the link above the line works:

![image](https://user-images.githubusercontent.com/1732545/121711931-6bca4a00-cadb-11eb-8f86-f31ad4f3ddb2.png)

**Comment by davidnussio** [comment]
Yes, is it. I used it on windows too.  After I recover the Windows pc and check if it still works (there has just been a vscode update ...)

**Comment by davidnussio** [comment]
I just tested it on windows and it's working correctly.
I suppose you are using **jq** language mode instead **jqpg** because the filter string is not highlighted and the ctrl+enter keymap is binded to languageId **jqpg**.
Try to change language mode to jqpg you would be see the jq filter line highlighted and try again.

**Comment by pixtur** [comment]
Ah excellent! I didn't pay attention to the language mode and didn't notice that there are two jq languages installed.
